### ISSUE TITLE
Unable to use ape inside of streamlit app

### ISSUE THREAD

**Issue by LinuxIsCool** [ApeWorX/ape#1164]
### Environment information

* Python 3.10.6
* eth-ape==0.5.6
* streamlit==1.15.1

I have a file called `index.py` that contains the following:  
```python
from ape import accounts
print(accounts[-1])     
```

And then in terminal, I run with:  
`streamlit run test.py`

And receive the following error:

```
(erc4626-py3.10) ygg@lemur ~/Workspace/Forks/ERC4626 [main] 🪷 streamlit run test.py                                                                                   ⌚ 15:16:02 

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://10.117.85.199:8501

2022-11-29 15:16:09.978 Uncaught app exception
Traceback (most recent call last):
  File "/home/ygg/.cache/pypoetry/virtualenvs/erc4626-bksimk3V-py3.10/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 564, in _run_script
    exec(code, module.__dict__)
  File "/home/ygg/Workspace/Forks/ERC4626/test.py", line 1, in <module>
    from ape import accounts
  File "/home/ygg/.cache/pypoetry/virtualenvs/erc4626-bksimk3V-py3.10/lib/python3.10/site-packages/ape/__init__.py", line 3, in <module>
    signal.signal(signal.SIGINT, lambda s, f: _sys.exit(130))
  File "/usr/lib/python3.10/signal.py", line 56, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter

```

Obviously, this is where things are breaking, but I don't understand what signal is or what it's used for:  
https://github.com/ApeWorX/ape/blob/350eff087d950e3abe904379bb91f13492b06eb1/src/ape/__init__.py#L3

**Comment by fubuloubu** [comment]
It came from this PR
https://github.com/ApeWorX/ape/issues/158
