### ISSUE TITLE
ApeX Doesn't Work with the Development Version of Web3.py

### ISSUE THREAD

**Issue by arjunaskykok** [ApeWorX/ape#1339]
### Environment information

- OS: linux
- Python version: 3.11
- `ape` and plugin versions:  the latest stable version

### What went wrong?

```bash
$ python3.11 -m venv .venv
$ source .venv/bin/activate
(.venv) $ pip install eth-ape
$ ape init
ImportError: cannot import name 'getargspec' from 'inspect' (/usr/lib/python3.11/inspect.py)
(.venv) $ pip install --upgrade https://github.com/ethereum/web3.py
ERROR: pip\'s dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
eth-ape 0.1.0a2 requires eth-account<0.6.0,>=0.5.4, but you have eth-account 0.8.0 which is incompatible.
(.venv) $ ape init
Traceback (most recent call last):
  File "/tmp/aa/.venv/bin/ape", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/tmp/aa/.venv/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/aa/.venv/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/tmp/aa/.venv/lib/python3.11/site-packages/click/core.py", line 1651, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/aa/.venv/lib/python3.11/site-packages/click/core.py", line 1698, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/aa/.venv/lib/python3.11/site-packages/ape/_cli/__init__.py", line 24, in get_command
    return CLI_PLUGINS[name]()
           ~~~~~~~~~~~^^^^^^
KeyError: 'init'
```

Right now, the fix for Python 3.11 has been put into the development version of web3.py. That's why I installed the web3.py library from GitHub.

**Comment by fubuloubu** [comment]
The version of ape it mentions is several versions back. Are you starting with the latest version of ape? Note that since we do not support 3.11 I think pip will downgrade you to the first pin that fits, if one exists. Some early alpha versions of ape didn't specify <3.11 so that could be the issue.

I think we could explore adding support for 3.11 if you want to open a PR to do that and see what breaks

**Comment by arjunaskykok** [comment]
> The version of ape it mentions is several versions back. Are you starting with the latest version of ape? Note that since we do not support 3.11 I think pip will downgrade you to the first pin that fits, if one exists. Some early alpha versions of ape didn't specify <3.11 so that could be the issue.
> 

With Python 3.11:
```bash
$ python3.11 -m venv .venv
$ source .venv/bin/activate
(.venv) $ pip install eth-ape
Collecting eth-ape
  Using cached eth_ape-0.1.0a2-py3-none-any.whl (12 kB)
```

With Python 3.10:
```bash
$ python3.10 -m venv .venv
$ source .venv/bin/activate
(.venv) $ pip install eth-ape
Collecting eth-ape
  Using cached eth_ape-0.6.5-py3-none-any.whl (217 kB)
```

So, it looks like Python 3.11 uses the old version of eth-ape.

> I think we could explore adding support for 3.11 if you want to open a PR to do that and see what breaks

Yeah, I'll look into it in my spare time. Created this bug just to let people know.

**Comment by fubuloubu** [comment]
Really could probably yank the alphas of ape from pypi so that this doesn't happen
