### ISSUE TITLE
bug: ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by mikeshultz** [ApeWorX/ape#1737]
### Environment information

- OS: linux
- Python Version: 3.10.13
- `ape` and plugin versions:

```sh
$ ape --version
0.6.25

$ ape plugins list
Traceback (most recent call last):
  File "/home/mike/.venvs/ape-test/bin/ape", line 8, in <module>
    sys.exit(cli())
  File "/home/mike/.venvs/ape-test/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/mike/.venvs/ape-test/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/mike/.venvs/ape-test/lib/python3.10/site-packages/ape/_cli.py", line 37, in invoke
    return super().invoke(ctx)
  File "/home/mike/.venvs/ape-test/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mike/.venvs/ape-test/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mike/.venvs/ape-test/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mike/.venvs/ape-test/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/mike/.venvs/ape-test/lib/python3.10/site-packages/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/mike/.venvs/ape-test/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/mike/.venvs/ape-test/lib/python3.10/site-packages/ape_plugins/_cli.py", line 102, in _list
    if output := metadata.to_str(include=to_display):
  File "/home/mike/.venvs/ape-test/lib/python3.10/site-packages/ape_plugins/utils.py", line 113, in to_str
    return str(ApePluginsRepr(self, include=include))
  File "/home/mike/.venvs/ape-test/lib/python3.10/site-packages/ape_plugins/utils.py", line 445, in __str__
    max_length = max(x.max_name_length for x in sections)
ValueError: max() arg is an empty sequenc
```

### What went wrong?

The above error when running `ape plugins list` with no plugins installed.

```bash
$ pip freeze | grep ape
eth-ape==0.6.25
```

If I install plugins, the command runs fine:

```bash
$ ape plugins list
Installed Plugins
  alchemy    0.6.5
  tokens     0.6.4
```

### How can it be fixed?

Return early with an empty string from [`ApePluginsRepr.__str__()`](https://github.com/ApeWorX/ape/blob/5dfc73367cee25d884b2bc4d908c49e04be951cc/src/ape_plugins/utils.py#L432-L445) when `sections` is empty?

**Comment by Aviksaikat** [comment]
I can take a look at this. Would like to get inputs from @fubuloubu @antazoey
