### ISSUE TITLE
ValueError: Invalid URL: port can't be converted to integer

### ISSUE THREAD

**Issue by Aviksaikat** [ApeWorX/ape#1752]
### Environment information

- OS: Linux
- Python Version: 3.9.0
- `ape` and plugin versions:

```sh
$ ape --version
0.6.26


$ ape plugins list
Installed Plugins
  alchemy      0.6.5
  etherscan    0.6.10
  foundry      0.6.19
  infura       0.6.5
  solidity     0.6.11

```

- Contents of your `ape-config.yaml` (NOTE: do not post anything private like RPC urls or secrets!):

```sh
$ cat ape-config.yaml
name: Get-Curve-Spot-Price
plugins:
  - name: solidity
  - name: alchemy
  - name: foundry
  - name: infura
  - name: etherscan
ethereum:
  default_network: mainnet-fork
  mainnet_fork:
    default_provider: foundry
    gas_limit: auto
    transaction_acceptance_timeout: 180
    default_transaction_type: 0
  mainnet:
    default_provider: alchemy
    transaction_acceptance_timeout: 180
foundry:
  fork:
    ethereum:
      mainnet_fork:
        upstream_provider: alchemy
test:
  mnemonic: test test test test test test test test test test test junk
  number_of_accounts: 10

```

### What went wrong?

Please include information like:
```sh
--- Logging error ---
Traceback (most recent call last):
  File "/home/avik/Desktop/git_projects/github_repos/Get-Curve-Spot-Price/.venv/lib/python3.9/site-packages/yarl/_url.py", line 191, in __new__
    port = val.port
  File "/usr/local/lib/python3.9/urllib/parse.py", line 175, in port
    raise ValueError(message) from None
ValueError: Port could not be cast to integer value as '8545,'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/avik/Desktop/git_projects/github_repos/Get-Curve-Spot-Price/.venv/lib/python3.9/site-packages/ape/logging.py", line 101, in emit
    msg = handler(msg)
  File "/home/avik/Desktop/git_projects/github_repos/Get-Curve-Spot-Price/.venv/lib/python3.9/site-packages/ape/api/providers.py", line 755, in _sanitize_web3_url
    sanitized_url = sanitize_url(rest[0])
  File "/home/avik/Desktop/git_projects/github_repos/Get-Curve-Spot-Price/.venv/lib/python3.9/site-packages/ape/logging.py", line 276, in sanitize_url
    url_obj = URL(url).with_user(None).with_password(None)
  File "/home/avik/Desktop/git_projects/github_repos/Get-Curve-Spot-Price/.venv/lib/python3.9/site-packages/yarl/_url.py", line 193, in __new__
    raise ValueError(
ValueError: Invalid URL: port can't be converted to integer
Call stack:
  File "/home/avik/Desktop/git_projects/github_repos/Get-Curve-Spot-Price/.venv/bin/ape", line 8, in <module>
    sys.exit(cli())
  File "/home/avik/Desktop/git_projects/github_repos/Get-Curve-Spot-Price/.venv/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/avik/Desktop/git_projects/github_repos/Get-Curve-Spot-Price/.venv/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/avik/Desktop/git_projects/github_repos/Get-Curve-Spot-Price/.venv/lib/python3.9/site-packages/ape/_cli.py", line 37, in invoke
    return super().invoke(ctx)
  File "/home/avik/Desktop/git_projects/github_repos/Get-Curve-Spot-Price/.venv/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/avik/Desktop/git_projects/github_repos/Get-Curve-Spot-Price/.venv/lib/python3.9/site-packages/ape_run/_cli.py", line 74, in invoke
    return super().invoke(ctx)
  File "/home/avik/Desktop/git_projects/github_repos/Get-Curve-Spot-Price/.venv/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/avik/Desktop/git_projects/github_repos/Get-Curve-Spot-Price/.venv/lib/python3.9/site-packages/ape/cli/commands.py", line 28, in invoke
    with networks.parse_network_choice(value, disconnect_on_exit=not interactive):
  File "/home/avik/Desktop/git_projects/github_repos/Get-Curve-Spot-Price/.venv/lib/python3.9/site-packages/ape/api/networks.py", line 611, in __enter__
    return self.push_provider()
  File "/home/avik/Desktop/git_projects/github_repos/Get-Curve-Spot-Price/.venv/lib/python3.9/site-packages/ape/api/networks.py", line 624, in push_provider
    self._provider.connect()
  File "/home/avik/Desktop/git_projects/github_repos/Get-Curve-Spot-Price/.venv/lib/python3.9/site-packages/ape_foundry/provider.py", line 946, in connect
    super().connect()
  File "/home/avik/Desktop/git_projects/github_repos/Get-Curve-Spot-Price/.venv/lib/python3.9/site-packages/ape_foundry/provider.py", line 315, in connect
    self._start()
  File "/home/avik/Desktop/git_projects/github_repos/Get-Curve-Spot-Price/.venv/lib/python3.9/site-packages/ape_foundry/provider.py", line 438, in _start
    self.start()
  File "/home/avik/Desktop/git_projects/github_repos/Get-Curve-Spot-Price/.venv/lib/python3.9/site-packages/ape/api/providers.py", line 1838, in start
    if self.is_connected:
  File "/home/avik/Desktop/git_projects/github_repos/Get-Curve-Spot-Price/.venv/lib/python3.9/site-packages/ape_foundry/provider.py", line 239, in is_connected
    self._set_web3()
  File "/home/avik/Desktop/git_projects/github_repos/Get-Curve-Spot-Price/.venv/lib/python3.9/site-packages/ape_foundry/provider.py", line 365, in _set_web3
    is_connected = self._web3.is_connected()
  File "/home/avik/Desktop/git_projects/github_repos/Get-Curve-Spot-Price/.venv/lib/python3.9/site-packages/web3/main.py", line 404, in is_connected
    return self.provider.is_connected(show_traceback)
  File "/home/avik/Desktop/git_projects/github_repos/Get-Curve-Spot-Price/.venv/lib/python3.9/site-packages/web3/providers/base.py", line 115, in is_connected
    response = self.make_request(RPCEndpoint("web3_clientVersion"), [])
  File "/home/avik/Desktop/git_projects/github_repos/Get-Curve-Spot-Price/.venv/lib/python3.9/site-packages/web3/providers/rpc.py", line 86, in make_request
    self.logger.debug(
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1422, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1577, in _log
    self.handle(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1587, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1649, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 948, in handle
    self.emit(record)
  File "/home/avik/Desktop/git_projects/github_repos/Get-Curve-Spot-Price/.venv/lib/python3.9/site-packages/ape/logging.py", line 109, in emit
    self.handleError(record)
Message: 'Making request HTTP. URI: http://127.0.0.1:8545, Method: web3_clientVersion'
Arguments: ()

```

### How can it be fixed?

I think the issue is happening from `ape 0.6.22` & later.

**Comment by Aviksaikat** [comment]
Yah there is somehow 1 extra `,` at the end or the RPC url

**Comment by fubuloubu** [comment]
> Yah there is somehow 1 extra `,` at the end or the RPC url

If you look at the string, there are 3 items in it that are separated by a period/comma:
1. `Making request HTTP`
2. `URI: http://127.0.0.1:8545`
3. `Method: web3_clientVersion`

Then each item is separated by a colon and a space

**Comment by Aviksaikat** [comment]
Maybe there's an extra space after the port. strip() should fix it ?

**Comment by fubuloubu** [comment]
> Maybe there's an extra space after the port. strip() should fix it ?

I think if you split the raw message up into the 3 sub-messages, then yes it will be easy to fix

**Comment by Aviksaikat** [comment]
Figured out the issue. trying to see if I can fix it without breaking aything

**Comment by Aviksaikat** [comment]
looks like it's fixed. Should I add some tests ?
