### ISSUE TITLE
bug: adhoc behavior unexpected

### ISSUE THREAD

**Issue by mikeshultz** [ApeWorX/ape#1761]
### Environment information

- OS: linux
- Python Version: 3.10
- `ape` and plugin versions:

```sh
$ ape --version
0.6.27

$ ape plugins list
Installed Plugins
  foundry    0.6.19
```

### What went wrong?

Websocket URIs not supported.  If you give a `--network` option begining with `ws://` it will return an error along the lines of:

```

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mike/.cache/pypoetry/virtualenvs/simtest-awk6WHKw-py3.10/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/mike/.cache/pypoetry/virtualenvs/simtest-awk6WHKw-py3.10/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/mike/.cache/pypoetry/virtualenvs/simtest-awk6WHKw-py3.10/lib/python3.10/site-packages/click/core.py", line 1686, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/home/mike/.cache/pypoetry/virtualenvs/simtest-awk6WHKw-py3.10/lib/python3.10/site-packages/click/core.py", line 943, in make_context
    self.parse_args(ctx, args)
  File "/home/mike/.cache/pypoetry/virtualenvs/simtest-awk6WHKw-py3.10/lib/python3.10/site-packages/click/core.py", line 1408, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/mike/.cache/pypoetry/virtualenvs/simtest-awk6WHKw-py3.10/lib/python3.10/site-packages/click/core.py", line 2400, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/home/mike/.cache/pypoetry/virtualenvs/simtest-awk6WHKw-py3.10/lib/python3.10/site-packages/click/core.py", line 2356, in process_value
    value = self.type_cast_value(ctx, value)
  File "/home/mike/.cache/pypoetry/virtualenvs/simtest-awk6WHKw-py3.10/lib/python3.10/site-packages/click/core.py", line 2344, in type_cast_value
    return convert(value)
  File "/home/mike/.cache/pypoetry/virtualenvs/simtest-awk6WHKw-py3.10/lib/python3.10/site-packages/click/core.py", line 2316, in convert
    return self.type(value, param=self, ctx=ctx)
  File "/home/mike/.cache/pypoetry/virtualenvs/simtest-awk6WHKw-py3.10/lib/python3.10/site-packages/click/types.py", line 83, in __call__
    return self.convert(value, param, ctx)
  File "/home/mike/.cache/pypoetry/virtualenvs/simtest-awk6WHKw-py3.10/lib/python3.10/site-packages/ape/cli/choices.py", line 351, in convert
    networks.get_provider_from_choice(network_choice=value)
  File "/home/mike/.cache/pypoetry/virtualenvs/simtest-awk6WHKw-py3.10/lib/python3.10/site-packages/ape/managers/networks.py", line 406, in get_provider_from_choice
    ecosystem = self.get_ecosystem(ecosystem_name or self.default_ecosystem.name)
  File "/home/mike/.cache/pypoetry/virtualenvs/simtest-awk6WHKw-py3.10/lib/python3.10/site-packages/ape/managers/networks.py", line 341, in get_ecosystem
    raise EcosystemNotFoundError(ecosystem_name, options=self.ecosystem_names)
ape.exceptions.EcosystemNotFoundError: No ecosystem named 'ws'. Options:
ethereum
```

### How can it be fixed?

Probably just include `ws://` and `wss://` in the pattern here?

https://github.com/ApeWorX/ape/blob/271a272ed7c35eb2c071e13d0bfcc3850a41f4a5/src/ape/cli/choices.py#L14

**Comment by fubuloubu** [comment]
We don't support general websocket connections yet in Ape though, a Websocket provider implementation would probably need to be created (or the current `Web3Provider` would need modifications to suppose using async websocket provider from web3py)

**Comment by mikeshultz** [comment]
Oh, my fault.  I had assumed it did since Silverback supports it (though I guess it translates).  Will leave this open though for the error message.

**Comment by antazoey** [comment]
Closing, but feel free to re-open a ticket focused on adding ws support in general

**Comment by antazoey** [comment]
oh seeing this, can fix https://github.com/ApeWorX/ape/issues/1761#issuecomment-1846344847
