### ISSUE TITLE
bug: parsed choice is not a parsable choice

### ISSUE THREAD

**Issue by mikeshultz** [ApeWorX/ape#1762]
### Environment information

- OS: linux
- Python Version: 3.10
- `ape` and plugin versions:

```sh
$ ape --version
0.6.27

$ ape plugins list
Installed Plugins
  foundry    0.6.19
```

### What went wrong?

This one might not be considered a bug, you tell me.

I would normally expect this to work, and it does for everything (that I know of) except adhoc:

```python
with self.network_manager.parse_network_choice(self.network_manager.network.choice):
    ...
```

However, since `.choice` is `ethereum:adhoc` instead of the given argument, which is a URI, it fails parsing.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mike/.cache/pypoetry/virtualenvs/simtest-awk6WHKw-py3.10/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/mike/.cache/pypoetry/virtualenvs/simtest-awk6WHKw-py3.10/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/mike/.cache/pypoetry/virtualenvs/simtest-awk6WHKw-py3.10/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mike/.cache/pypoetry/virtualenvs/simtest-awk6WHKw-py3.10/lib/python3.10/site-packages/ape/cli/commands.py", line 29, in invoke
    super().invoke(ctx)
  File "/home/mike/.cache/pypoetry/virtualenvs/simtest-awk6WHKw-py3.10/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mike/.cache/pypoetry/virtualenvs/simtest-awk6WHKw-py3.10/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/mike/dev/simulation-test/simtest/cli.py", line 30, in watch
    run_watchbot()
  File "/home/mike/dev/simulation-test/simtest/watchbot/__init__.py", line 26, in run_watchbot
    app = create_watchbot()
  File "/home/mike/dev/simulation-test/simtest/watchbot/__init__.py", line 16, in create_watchbot
    app = SilverbackApp()
  File "/home/mike/dev/silverback/silverback/application.py", line 41, in __init__
    self.network = settings.get_provider_context()
  File "/home/mike/dev/silverback/silverback/settings.py", line 81, in get_provider_context
    return self.network_manager.parse_network_choice(self.get_network_choice())
  File "/home/mike/.cache/pypoetry/virtualenvs/simtest-awk6WHKw-py3.10/lib/python3.10/site-packages/ape/managers/networks.py", line 446, in parse_network_choice
    provider = self.get_provider_from_choice(
  File "/home/mike/.cache/pypoetry/virtualenvs/simtest-awk6WHKw-py3.10/lib/python3.10/site-packages/ape/managers/networks.py", line 400, in get_provider_from_choice
    network = ecosystem.get_network(network_name or ecosystem.default_network)
  File "/home/mike/.cache/pypoetry/virtualenvs/simtest-awk6WHKw-py3.10/lib/python3.10/site-packages/ape/api/networks.py", line 443, in get_network
    raise NetworkNotFoundError(network_name, ecosystem=self.name, options=self.networks)
ape.exceptions.NetworkNotFoundError: No network in 'ethereum' named 'adhoc'. Options:
goerli
goerli-fork
local
mainnet
mainnet-fork
sepolia
sepolia-fork
```

Maybe I'm just going about this wrong and this isn't good API usage.

### How can it be fixed?

Got me bruh

**Comment by antazoey** [comment]
I think the easiest solution until we improve adhoc connections is to have adhoc networks return the URI for choice

**Comment by antazoey** [comment]
So `self.network_manager.network.choice` returns the network choice without the provider.
For the full network triple, you would want: `self.chain.provider.choice`.

**Comment by antazoey** [comment]
But yeah, `network.choice` will NOT include the provider part, you need `provider.network_choice` (sorry for confusing naming), which has the full triple.

This will always fail because you need to give it the URL:

```python
self.network_manager.parse_network.choice("ethereum:custom")
```

But this will work:

```python
self.network_manager.parse_network.choice("ethereum:custom:https://path/to.node.com")
```

should work, I just need to make the provider choice return the URI in this case (doing that now)

(btw adhoc was renamed to custom in 0.7)
