### ISSUE TITLE
ape fails to parse Mint events from UniswapV3Pool contract

### ISSUE THREAD

**Issue by pyggie** [ApeWorX/ape#1896]
### Environment information

- OS: macOS / linux / win
```
Linux (Ubuntu 20.04.3 LTS)
```

- Python Version: x.x.x
```sh
$ python3 --version
Python 3.8.10
```

- `ape` and plugin versions:

```sh
$ ape --version
0.7.6

$ ape plugins list
Installed Plugins
  alchemy      0.7.1
  etherscan    0.7.0
  foundry      0.7.3
  solidity     0.7.1
```

- Contents of your `ape-config.yaml` (NOTE: do not post anything private like RPC urls or secrets!):

```sh
$ cat ape-config.yaml
name: test

plugins:
  - name: solidity
  - name: foundry
  - name: alchemy
  - name: etherscan

default_ecosystem: ethereum

ethereum:
  default_network: mainnet
  mainnet:
    default_provider: alchemy
```

### What went wrong?

I tried to parse Mint events from a UniswapV3 pool. Ape threw an error while parsing the logs, apparently while trying to convert a signed int24 to an address.

Given this input:
```
from ape import networks, Contract                                                                                                               
networks.parse_network_choice('ethereum:mainnet').__enter__()
poolAddr = '0x3416cF6C708Da44DB2624D63ea0AAef7113527C6'  # UniV3 USDC-USDT 1bps
univ3pool = Contract(poolAddr)   # this relies on etherscan plugin to fetch contract ABI
blockNum = univ3pool.receipt.block_number
logs = univ3pool.Mint.query('*', start_block=blockNum, stop_block=blockNum)
```

Ape throws this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/home/user/.local/pipx/venvs/eth-ape/lib/python3.8/site-packages/ape/contracts/base.py", line 572, in query
    contract_events = self.query_manager.query(
  File "/mnt/home/user/.local/pipx/venvs/eth-ape/lib/python3.8/site-packages/ape/managers/query.py", line 212, in query
    engine.update_cache(query, cache_data)
  File "/mnt/home/user/.local/pipx/venvs/eth-ape/lib/python3.8/site-packages/ape_cache/query.py", line 464, in update_cache
    self._get_cache_data(query, result)
  File "/usr/lib/python3.8/functools.py", line 912, in _method
    return method.__get__(obj, cls)(*args, **kwargs)
  File "/mnt/home/user/.local/pipx/venvs/eth-ape/lib/python3.8/site-packages/ape_cache/query.py", line 447, in _get_cache_events_data
    return [m.model_dump(mode="json", by_alias=False) for m in result]
  File "/mnt/home/user/.local/pipx/venvs/eth-ape/lib/python3.8/site-packages/ape_cache/query.py", line 447, in <listcomp>
    return [m.model_dump(mode="json", by_alias=False) for m in result]
  File "/mnt/home/user/.local/pipx/venvs/eth-ape/lib/python3.8/site-packages/ape_ethereum/provider.py", line 813, in get_contract_logs
    yield from page
  File "/mnt/home/user/.local/pipx/venvs/eth-ape/lib/python3.8/site-packages/ape_ethereum/ecosystem.py", line 882, in decode_logs
    converted_arguments[key] = self.decode_address(value)
  File "/mnt/home/user/.local/pipx/venvs/eth-ape/lib/python3.8/site-packages/ape_ethereum/ecosystem.py", line 345, in decode_address
    return to_checksum_address(HexBytes(raw_address)[-20:].rjust(20, b"\x00"))
  File "/mnt/home/user/.local/pipx/venvs/eth-ape/lib/python3.8/site-packages/hexbytes/main.py", line 42, in __new__
    bytesval = to_bytes(val)
  File "/mnt/home/user/.local/pipx/venvs/eth-ape/lib/python3.8/site-packages/hexbytes/_utils.py", line 26, in to_bytes
    raise ValueError(f"Cannot convert negative integer {val} to bytes")
ValueError: Cannot convert negative integer -4 to bytes
```

The Mint event is defined as:
```
   event Mint(
        address sender,
        address indexed owner,
        int24 indexed tickLower,
        int24 indexed tickUpper,
        uint128 amount,
        uint256 amount0,
        uint256 amount1
    );
```
See  IUniswapV3PoolEvents.sol at https://etherscan.io/address/0x3416cf6c708da44db2624d63ea0aaef7113527c6#code#F28#L21

(The docs at https://docs.uniswap.org/contracts/v3/reference/core/interfaces/pool/IUniswapV3PoolEvents omit the `indexed` modifiers.)

### How can it be fixed?

In `ape_ethereum/ecosystem.py` `decode_logs()`, the order of items in `event_arguments` does not match the order of items in `abi.abi.inputs`, but they are joined in order by `zip()`. In `event_arguments`, the indexed topics come first, while in `abi.abi.inputs` the arguments match the event definition.

```
event_arguments.items(): [
  {'owner': '0xc36442b4a4522e871399cd717abdd847ab11fe88'}
  {'tickLower': -4}
  {'tickUpper': 4}
  {'sender': '0xc36442b4a4522e871399cd717abdd847ab11fe88'}
  {'amount': 36624092642042107}
  {'amount0': 10986129216312}
  {'amount1': 3661676892209}
]
```
while
```
abi.abi.inputs: [
  name='sender' type='address' components=None internal_type='address' indexed=False
  name='owner' type='address' components=None internal_type='address' indexed=True
  name='tickLower' type='int24' components=None internal_type='int24' indexed=True
  name='tickUpper' type='int24' components=None internal_type='int24' indexed=True
  name='amount' type='uint128' components=None internal_type='uint128' indexed=False
  name='amount0' type='uint256' components=None internal_type='uint256' 
indexed=False
  name='amount1' type='uint256' components=None internal_type='uint256' indexed=False
]
```

To fix this, you could traverse `abi.abi.inputs` and look up the value in `event_arguments`. Something like replacing line 868:

```
            for _type, (key, value) in zip(_types, event_arguments.items()):                                                       
```
with
```
            for item in abi.abi.inputs:
                _type = item.canonical_type
                key = item.name
                value = event_arguments[key]
```

**Comment by antazoey** [comment]
thanks for reporting; im on it
