### ISSUE TITLE
bug: object has no attribute '__isabstractmethod__'

### ISSUE THREAD

**Issue by mikeshultz** [ApeWorX/ape#2053]
### Environment information

- OS: linux
- Python Version: 3.11.8
- `ape` and plugin versions:

```sh
$ ape --version
0.7.19

$ ape plugins list
Installed Plugins
  alchemy    0.7.2
```

### What went wrong?

This seems to occur early in execution, probably during imports/init.  This doesn't crash the process or anything, but I assume there's some adverse effect happening here.

I wish I had better better tracebacks.  I haven't been able to repro this yet via simple ape commands.  Still looking into it:

```
DEBUG: Traceback (most recent call last):
  File "/home/mike/.venvs/silverback-cluster/lib/python3.11/site-packages/ape/utils/basemodel.py", line 110, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/mike/.venvs/silverback-cluster/lib/python3.11/site-packages/ape/api/config.py", line 72, in __getattr__
    return super().__getattribute__(attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NetworkConfig' object has no attribute '__isabstractmethod__'

DEBUG: Traceback (most recent call last):
  File "/home/mike/.venvs/silverback-cluster/lib/python3.11/site-packages/ape/utils/basemodel.py", line 110, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/mike/.venvs/silverback-cluster/lib/python3.11/site-packages/ape/api/config.py", line 72, in __getattr__
    return super().__getattribute__(attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NetworkConfig' object has no attribute '__isabstractmethod__'

DEBUG: Traceback (most recent call last):
  File "/home/mike/.venvs/silverback-cluster/lib/python3.11/site-packages/ape/utils/basemodel.py", line 110, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/mike/.venvs/silverback-cluster/lib/python3.11/site-packages/ape/api/config.py", line 72, in __getattr__
    return super().__getattribute__(attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NetworkConfig' object has no attribute '__isabstractmethod__'

DEBUG: Traceback (most recent call last):
  File "/home/mike/.venvs/silverback-cluster/lib/python3.11/site-packages/ape/utils/basemodel.py", line 110, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/mike/.venvs/silverback-cluster/lib/python3.11/site-packages/ape/api/config.py", line 72, in __getattr__
    return super().__getattribute__(attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GethNetworkConfig' object has no attribute '__isabstractmethod__'

DEBUG: Traceback (most recent call last):
  File "/home/mike/.venvs/silverback-cluster/lib/python3.11/site-packages/ape/utils/basemodel.py", line 110, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/mike/.venvs/silverback-cluster/lib/python3.11/site-packages/ape/api/config.py", line 72, in __getattr__
    return super().__getattribute__(attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CoverageReportsConfig' object has no attribute '__isabstractmethod__'

DEBUG: Traceback (most recent call last):
  File "/home/mike/.venvs/silverback-cluster/lib/python3.11/site-packages/ape/utils/basemodel.py", line 110, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/mike/.venvs/silverback-cluster/lib/python3.11/site-packages/ape/api/config.py", line 72, in __getattr__
    return super().__getattribute__(attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GasConfig' object has no attribute '__isabstractmethod__'

DEBUG: Traceback (most recent call last):
  File "/home/mike/.venvs/silverback-cluster/lib/python3.11/site-packages/ape/utils/basemodel.py", line 110, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/mike/.venvs/silverback-cluster/lib/python3.11/site-packages/ape/api/config.py", line 72, in __getattr__
    return super().__getattribute__(attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CoverageConfig' object has no attribute '__isabstractmethod__'

DEBUG: Traceback (most recent call last):
  File "/home/mike/.venvs/silverback-cluster/lib/python3.11/site-packages/ape/utils/basemodel.py", line 110, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/mike/.venvs/silverback-cluster/lib/python3.11/site-packages/ape/api/config.py", line 72, in __getattr__
    return super().__getattribute__(attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'EthTesterProviderConfig' object has no attribute '__isabstractmethod__'
```

**Comment by mikeshultz** [comment]
I'm able to repro this via `ape -v DEBUG console`.  So these exceptions are being handled and logged somewhere.
