### ISSUE TITLE
CLI_PLUGINS doesn't include accounts

### ISSUE THREAD

**Issue by nazariyv** [ApeWorX/ape#330]
### Environment information

Ubuntu 20.04

* `ape` and plugin versions:

version = '0.1.0a2'

$ ape --version

```
Traceback (most recent call last):
  File "/home/shredder/.v/apeworx/bin/ape", line 8, in <module>
    sys.exit(cli())
  File "/home/shredder/.v/apeworx/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/shredder/.v/apeworx/lib/python3.10/site-packages/click/core.py", line 1052, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/home/shredder/.v/apeworx/lib/python3.10/site-packages/click/core.py", line 914, in make_context
    self.parse_args(ctx, args)
  File "/home/shredder/.v/apeworx/lib/python3.10/site-packages/click/core.py", line 1615, in parse_args
    rest = super().parse_args(ctx, args)
  File "/home/shredder/.v/apeworx/lib/python3.10/site-packages/click/core.py", line 1370, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/shredder/.v/apeworx/lib/python3.10/site-packages/click/core.py", line 2347, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/home/shredder/.v/apeworx/lib/python3.10/site-packages/click/core.py", line 2309, in process_value
    value = self.callback(ctx, self, value)
  File "/home/shredder/.v/apeworx/lib/python3.10/site-packages/click/decorators.py", line 380, in callback
    raise RuntimeError(
RuntimeError: 'ape' is not installed. Try passing 'package_name' instead.
```

$ ape plugins list
```KeyError: 'plugins'```

* Python Version: 3.10.1
* OS: linux

### What went wrong?

Please include information like:

* what command you ran
`ape accounts list`

### How can it be fixed?

I have inserted a breakpoint just before the failing line this is what comes up when I run `dir(CLI_PLUGINS)`

```
> /home/shredder/.v/apeworx/lib/python3.10/site-packages/ape/_cli/__init__.py(25)get_command()
-> return CLI_PLUGINS[name]()
(Pdb) dir(CLI_PLUGINS)
['__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__ior__', '__iter__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__ror__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'clear', 'copy', 'fromkeys', 'get', 'items', 'keys', 'move_to_end', 'pop', 'popitem', 'setdefault', 'update', 'values']
```

As can be seen from the above, there is no `accounts` or `plugins` or any cli commands for that matter.

**Comment by nazariyv** [comment]
And the cause of the above missing the cli plugins is because `discovered_plugins` is an empty list, upon further inspection.

**Comment by nazariyv** [comment]
I think I am on the wrong ape version and have to build from source here

**Comment by nazariyv** [comment]
Installing via setuptools at the latest commit: `fd95`, however, produces the following error

```
Traceback (most recent call last):
  File "/home/shredder/.v/apeworx/bin/ape", line 33, in <module>
    sys.exit(load_entry_point('eth-ape==0.1.0b2.dev1+gfd9583b6', 'console_scripts', 'ape')())
  File "/home/shredder/.v/apeworx/bin/ape", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/shredder/.pyenv/versions/3.10.1/lib/python3.10/importlib/metadata/__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "/home/shredder/.pyenv/versions/3.10.1/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/shredder/.v/apeworx/lib/python3.10/site-packages/eth_ape-0.1.0b2.dev1+gfd9583b6-py3.10.egg/ape/__init__.py", 
line 9, in <module>
    from .contracts import _Contract
  File "/home/shredder/.v/apeworx/lib/python3.10/site-packages/eth_ape-0.1.0b2.dev1+gfd9583b6-py3.10.egg/ape/contracts/__init__.py", line 1, in <module>
    from .base import ContractContainer, ContractInstance, ContractLog, _Contract
  File "/home/shredder/.v/apeworx/lib/python3.10/site-packages/eth_ape-0.1.0b2.dev1+gfd9583b6-py3.10.egg/ape/contracts/base.py", line 3, in <module>
    from eth_utils import to_bytes
  File "/home/shredder/.v/apeworx/lib/python3.10/site-packages/eth_utils/__init__.py", line 4, in <module>
    import pkg_resources
  File "/home/shredder/.v/apeworx/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/home/shredder/.v/apeworx/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside       
    f(*args, **kwargs)
  File "/home/shredder/.v/apeworx/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/shredder/.v/apeworx/lib/python3.10/site-packages/pkg_resources/__init__.py", line 568, in _build_master      
    ws.require(__requires__)
  File "/home/shredder/.v/apeworx/lib/python3.10/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/shredder/.v/apeworx/lib/python3.10/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'packaging' distribution was not found and is required by pytest
```

**Comment by fubuloubu** [comment]
Oh hold on, note that we don't support 3.10 yet!

See #235

Will work on Py 3.10 support asap

**Comment by fubuloubu** [comment]
@nazariyv just released `0.1.0b2` with Python 3.10 support. Try it again and let me know if your issue is cleared up

**Comment by unparalleled-js** [comment]
Something to keep in mind - even if we get 3.10 to work, it is not "officially" supported in many of our dependencies yet, such as `click`. In general, we should wait until our dependencies are ready before trying to support 3.10.

https://pyreadiness.org/3.10/

**Comment by fubuloubu** [comment]
yes, I might have jumped too quickly on this :grimacing:

**Comment by unparalleled-js** [comment]
I just installed python 3.10.1 and ran the tests in my demo project and everything worked 🤷🏻‍♀️ 

I think we should allow it to work without "officially" supporting it, if possible

**Comment by nazariyv** [comment]
I believe I have had other issues with Python 3.7.12, the only version that I think I got to work was 3.8.12

**Comment by fubuloubu** [comment]
> I believe I have had other issues with Python 3.7.12, the only version that I think I got to work was 3.8.12

I've never heard of anyone with issues on 3.8 or 3.9

**Comment by fubuloubu** [comment]
> I believe I have had other issues with Python 3.7.12, the only version that I think I got to work was 3.8.12

actually, what issue were you having with 3.7?

**Comment by nazariyv** [comment]
during `pip install eth-ape`:

```
...
ERROR: web3 5.25.0 has requirement typing-extensions<4,>=3.7.4.1, but you'll have typing-extensions 4.0.1 which is incompatible.
ERROR: trie 2.0.0a5 has requirement typing-extensions<4,>=3.7.4, but you'll have typing-extensions 4.0.1 which is incompatible.
...
```

**Comment by nazariyv** [comment]
> I've never heard of anyone with issues on 3.8 or 3.9

Ignore me on this, looks like it is working.

**Comment by nazariyv** [comment]
happy to close the issue, since 3.8.12 is working for me

**Comment by fubuloubu** [comment]
> > I've never heard of anyone with issues on 3.8 or 3.9
> 
> Ignore me on this, looks like it is working.

Yes @unparalleled-js just fixed this!
