### ISSUE TITLE
KeyError when parsing network choice

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#514]
### Environment information

* `ape` and plugin versions:

```
$ ape --version
0.1.0b5.dev63+gc7c38c2e

$ ape plugins list
Installed Plugins:
  fantom          0.1.dev3+gfd2478a
```

* Python Version: x.x.x
* OS: macOS/linux/win

### What went wrong?

```sh
$ ape console
Traceback (most recent call last):
  File "/home/bryant/.pyenv/versions/ape-fantom/bin/ape", line 33, in <module>
    sys.exit(load_entry_point('eth-ape', 'console_scripts', 'ape')())
  File "site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "site-packages/ape/_cli.py", line 40, in invoke
    return super().invoke(ctx)
  File "site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "site-packages/ape/cli/commands.py", line 17, in invoke
    with networks.parse_network_choice(value):
  File "site-packages/ape/managers/networks.py", line 278, in parse_network_choice
    provider = self.get_provider_from_choice(
  File "site-packages/ape/managers/networks.py", line 230, in get_provider_from_choice
    return ecosystem[default_network].get_provider(provider_settings=provider_settings)
  File "site-packages/ape/api/networks.py", line 502, in get_provider
    return self.providers[provider_name](provider_settings=provider_settings)
  File "<string>", line 10, in __init__
  File "site-packages/ape_test/providers.py", line 24, in __post_init__
    self.config["mnemonic"], num_accounts=self.config["number_of_accounts"]
  File "site-packages/ape/api/config.py", line 67, in __getitem__
    raise KeyError(f"{attrname!r}")
KeyError: "'mnemonic'"
```

### How can it be fixed?
Not sure why `mnemonic` is being used here

**Comment by fubuloubu** [comment]
Seems this is only the case when using an ecosystem plugin on `main` right now?

**Comment by fubuloubu** [comment]
okay weird, this might be that the config for fantom's `test` provider plugin is empty (doesn't contain `mnemonic`)
