### ISSUE TITLE
ape.compilers.compile fails to compile in script

### ISSUE THREAD

**Issue by johnson2427** [ApeWorX/ape#523]
### Environment information

* `ape` and plugin versions:

```
$ ape --version
0.1.0b6.dev38+ge5839c1c.d20220228

$ ape plugins list
ape-infura
ape-vyper
```

* Python Version: 3.8.10
* OS: Ubuntu 20.04

### What went wrong?

* what script you ran
```python
from ape import chain, networks, accounts, project
from ape import compilers

compilers.compile(["contracts/Token.vy"])
```
* Full output of error:
```
Traceback (most recent call last):
  File "/snap/pycharm-professional/271/plugins/python/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-professional/271/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/blake/ApeWorX/ape/scratch/file.py", line 10, in <module>
    compilers.compile(["contracts/Token.vy"])
  File "/home/blake/ApeWorX/ape/src/ape/managers/compilers.py", line 85, in compile
    extensions = self._get_contract_extensions(contract_filepaths)
  File "/home/blake/ApeWorX/ape/src/ape/managers/compilers.py", line 110, in _get_contract_extensions
    extensions = set(path.suffix for path in contract_filepaths)
  File "/home/blake/ApeWorX/ape/src/ape/managers/compilers.py", line 110, in <genexpr>
    extensions = set(path.suffix for path in contract_filepaths)
AttributeError: 'str' object has no attribute 'suffix'
python-BaseException
```

### How can it be fixed?

Use a method that splits the suffix rather than relying on class methods to handle this

**Comment by fubuloubu** [comment]
Need to pass a Path, no a string
