### ISSUE TITLE
ape console fails to load on macOS 12.2 w/ venv

### ISSUE THREAD

**Issue by punkZK** [ApeWorX/ape#529]
### Environment information

* `ape` and plugin versions:

```
$ ape --version
0.1.0b5

$ ape plugins list
No secondary plugins installed. Use '--all' to see available plugins.

* Python Version: 3.8.12
* OS: macOS 12.2.1 (21D62)
```

### What went wrong?

I freshly installed "ape" on my macbook and was testing each of the high level commands and noticed that one of the commands "console" did not Error out gracefully.

* what command you ran
ape console

* full output of the error you received

```bash
(ape_venv) ZKPunks-MacBook-Pro:ape_experiments ZKPunk$ ape console
Traceback (most recent call last):
  File "/Users/ZKPunk/py_venv/ape_venv/bin/ape", line 8, in <module>
    sys.exit(cli())
  File "/Users/ZKPunk/py_venv/ape_venv/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ZKPunk/py_venv/ape_venv/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/ZKPunk/py_venv/ape_venv/lib/python3.8/site-packages/ape/_cli.py", line 40, in invoke
    return super().invoke(ctx)
  File "/Users/ZKPunk/py_venv/ape_venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ZKPunk/py_venv/ape_venv/lib/python3.8/site-packages/ape/cli/commands.py", line 18, in invoke
    super().invoke(ctx)
  File "/Users/ZKPunk/py_venv/ape_venv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ZKPunk/py_venv/ape_venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/ZKPunk/py_venv/ape_venv/lib/python3.8/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/ZKPunk/py_venv/ape_venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/ZKPunk/py_venv/ape_venv/lib/python3.8/site-packages/ape_console/_cli.py", line 24, in cli
    return console(verbose=verbose)
  File "/Users/ZKPunk/py_venv/ape_venv/lib/python3.8/site-packages/ape_console/_cli.py", line 61, in console
    IPython.embed(colors="Neutral", banner1=banner, user_ns=namespace)
  File "/Users/ZKPunk/py_venv/ape_venv/lib/python3.8/site-packages/IPython/terminal/embed.py", line 397, in embed
    shell = InteractiveShellEmbed.instance(_init_location_id='%s:%s' % (
  File "/Users/ZKPunk/py_venv/ape_venv/lib/python3.8/site-packages/traitlets/config/configurable.py", line 540, in instance
    inst = cls(*args, **kwargs)
  File "/Users/ZKPunk/py_venv/ape_venv/lib/python3.8/site-packages/IPython/terminal/embed.py", line 168, in __init__
    super(InteractiveShellEmbed,self).__init__(**kw)
  File "/Users/ZKPunk/py_venv/ape_venv/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 619, in __init__
    super(TerminalInteractiveShell, self).__init__(*args, **kwargs)
  File "/Users/ZKPunk/py_venv/ape_venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 529, in __init__
    self.init_virtualenv()
  File "/Users/ZKPunk/py_venv/ape_venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 788, in init_virtualenv
    new_path = p.readlink()
AttributeError: 'PosixPath' object has no attribute 'readlink'
```

### How can it be fixed?

I am yet to dig into the actual cause of the error; maybe "console" expects a plugin to be installed, if thats the case it should still be handled gracefully.

**Comment by unparalleled-js** [comment]
Hello and thank-you for testing and finding an issue 🙂

Are you running some code within  ape console? Or does this error happen when you just do ape console alone?
I have not experienced this - when exceptions happen, the intent is that you see them in your console session and the IPython shell does not exit.

**Comment by fubuloubu** [comment]
Also what virtualenv are you using? I see `init_virtualenv` in the stack trace, making me think it's related to that.

Probably a good quetsion to ask on the issue template.... :thinking:

**Comment by punkZK** [comment]
# virtualenv --version
virtualenv 20.4.3 from /usr/local/lib/python3.8/site-packages/virtualenv/__init__.py

The commands on my shell history
```
# cd ~/py_venv/
# python3 -m venv ape_venv
# mkdir ape_experiments
# cd ape_experiments/
# source ~/py_venv/ape_venv/bin/activate
# pip install eth-ape
# pip install --upgrade pip

```

**Comment by punkZK** [comment]
Looks like updating "pip" before installing "ape" fixes the issue!

**Comment by fubuloubu** [comment]
for those reading at home, run this first before installing `eth-ape`:

```sh
$ pip install -U pip
```
