### ISSUE TITLE
ape doesn't launch via python3.10.4 pip

### ISSUE THREAD

**Issue by ngmisl** [ApeWorX/ape#769]
### Environment information

* linux
* Python Version: 3.10.4

### What went wrong?

Trying to launch ape installed via pip in the env:

```
Traceback (most recent call last):
  File "/home/x/dev/ape/demo/env/bin/ape", line 5, in <module>
    from ape._cli import cli
  File "/home/x/dev/ape/demo/env/lib/python3.10/site-packages/ape/__init__.py", line 7, in <module>
    from ape.managers.project import ProjectManager as Project
  File "/home/x/dev/ape/demo/env/lib/python3.10/site-packages/ape/managers/__init__.py", line 3, in <module>
    from ape.plugins import PluginManager
  File "/home/x/dev/ape/demo/env/lib/python3.10/site-packages/ape/plugins/__init__.py", line 9, in <module>
    from .account import AccountPlugin
  File "/home/x/dev/ape/demo/env/lib/python3.10/site-packages/ape/plugins/account.py", line 3, in <module>
    from ape.api.accounts import AccountAPI, AccountContainerAPI
  File "/home/x/dev/ape/demo/env/lib/python3.10/site-packages/ape/api/__init__.py", line 25, in <module>
    from .query import QueryAPI, QueryType
  File "/home/x/dev/ape/demo/env/lib/python3.10/site-packages/ape/api/query.py", line 3, in <module>
    import pandas as pd
  File "/home/x/dev/ape/demo/env/lib/python3.10/site-packages/pandas/__init__.py", line 48, in <module>
    from pandas.core.api import (
  File "/home/x/dev/ape/demo/env/lib/python3.10/site-packages/pandas/core/api.py", line 48, in <module>
    from pandas.core.groupby import (
  File "/home/x/dev/ape/demo/env/lib/python3.10/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/home/x/dev/ape/demo/env/lib/python3.10/site-packages/pandas/core/groupby/generic.py", line 70, in <module>
    from pandas.core.frame import DataFrame
  File "/home/x/dev/ape/demo/env/lib/python3.10/site-packages/pandas/core/frame.py", line 157, in <module>
    from pandas.core.generic import NDFrame
  File "/home/x/dev/ape/demo/env/lib/python3.10/site-packages/pandas/core/generic.py", line 129, in <module>
    from pandas.core.describe import describe_ndframe
  File "/home/x/dev/ape/demo/env/lib/python3.10/site-packages/pandas/core/describe.py", line 38, in <module>
    from pandas.io.formats.format import format_percentiles
  File "/home/x/dev/ape/demo/env/lib/python3.10/site-packages/pandas/io/formats/format.py", line 99, in <module>
    from pandas.io.common import (
  File "/home/x/dev/ape/demo/env/lib/python3.10/site-packages/pandas/io/common.py", line 4, in <module>
    import bz2
  File "/home/x/.pyenv/versions/3.10.4/lib/python3.10/bz2.py", line 17, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'
```

**Comment by fubuloubu** [comment]
when installing a python version with pyenv on linux, I've found that there are a number of libraries which improve the install experience you should have installed via `apt`:

```sh
$ sudo apt install zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev tk-dev libssl-dev llvm \
libncurses5-dev libncursesw5-dev xz-utils libffi-dev liblzma-dev python-openssl
```

**Comment by ngmisl** [comment]
I still get the same errors, unfortunately :(

**Comment by ngmisl** [comment]
Another problem:

`❯ ape compile
WARNING: No compilers detected for the following extensions: .vy`

but I can compile it manually via vyper

**Comment by gosuto-inzasheru** [comment]
this appears to be a problem with some other dependencies in your env (pandas?). i dont think this is related to python 3.10.4 or even eth-ape.

i tried to reproduce locally, but could only try so using 3.10.8. did not encounter any problems.
